<script type="text/javascript">
    var mainContainer = null;
    (function($) {
        $(document).on('ready', function() {
            mainContainer = new WidgetMainContainer('body');
            new WidgetAddWidget( mainContainer, {Web:{widgets:['WidgetContainer'], open:true}} );
            $('.overlay').on('click', function(){
                $('.widget-add').removeClass('clicked').removeClass('col-md-3').addClass('col-md-2');
                $('.overlay').hide();
                $('.content',$('.widget-add')).removeClass('height-2').addClass('height-1');
            });
        });

        $( document ).on( "click", "i.fa.fa-cog", function(evt) {
            $(evt.target.parentNode.parentNode.parentNode).toggleClass('active');
        });

    })(jQuery);
</script>