<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Demo')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/style.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ->prependStylesheet('//fonts.googleapis.com/css?family=Pacifico|Roboto+Condensed')
        ->prependStylesheet($this->basePath() . '/css/vendor/simplecolorpicker.css')
        ->prependStylesheet( '//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css')?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/vendor/jquery.simplecolorpicker.js')
        ->prependFile($this->basePath() . '/js/protohype/WidgetEmpty.js')
        ->prependFile($this->basePath() . '/js/protohype/WidgetContainer.js')
        ->prependFile($this->basePath() . '/js/protohype/WidgetHTML.js')
        ->prependFile($this->basePath() . '/js/protohype/WidgetVideo.js')
        ->prependFile($this->basePath() . '/js/protohype/WidgetMainContainer.js')
        ->prependFile($this->basePath() . '/js/protohype/WidgetProperties.js')
        ->prependFile($this->basePath() . '/js/protohype/WidgetLikedList.js')
        ->prependFile($this->basePath() . '/js/protohype/WidgetDummies.js')
        ->prependFile($this->basePath() . '/js/protohype/WidgetAddWidget.js')
        ->prependFile($this->basePath() . '/js/vendor/ckeditor/config.js')
        ->prependFile($this->basePath() . '/js/vendor/ckeditor/ckeditor.js')
        ->prependFile($this->basePath() . '/js/vendor/bootbox.min.js')
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile('//player.ooyala.com/v3/45aed09ccb8c493b964b666b1ece09c5')

    ; ?>

</head>
<body class="page-editor">
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div>
        <div class="navbar-header">
            <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/mascot.png') ?>" alt="Protohype!"/><span>Protohype!</span> <i class="fa fa-sort-desc"></i> </a>
        </div>
        <div class="arrow-right"></div>

        <?php if( $this->hasIdentity ) : ?>
            <ul class="nav navbar-top-links navbar-right">
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <span class="user-info"><?php echo $this->layout()->identity->name; ?></span>
                        <?php echo $this->gravatar($this->identity->email, array('class'=>"nav-user-photo"),  array('class'=>"nav-user-photo"))?>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user fa-fw"></i> Profile</a>
                        </li>
                        <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li><a href="/auth/logout"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
        <?php endif; ?>
    </div>
</nav>

<div class="main-content content clearfix">
<?php echo $this->content; ?>
</div>
<div class="overlay"></div>
<?php echo $this->inlineScript() ?>
</body>
</html>
