<div class="row websites-container">
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-globe"></i> Website #1</h3>
            </div>
            <div class="panel-body">
                <div class="icon"><i class="fa fa-file-code-o"></i></div>
                <p>The website Description</p>
                <p><a class="btn btn-success pull-right" href="#" ><i class="fa fa-pencil-square-o"></i> <?php echo $this->translate('Edit') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-globe"></i> Website #2</h3>
            </div>
            <div class="panel-body">
                <div class="icon"><i class="fa fa-file-code-o"></i></div>
                <p>The website Description</p>
                <p><a class="btn btn-success pull-right" href="#" ><i class="fa fa-pencil-square-o"></i> <?php echo $this->translate('Edit') ?> &raquo;</a></p>

            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-globe"></i> Website #3</h3>
            </div>
            <div class="panel-body">
                <div class="icon"><i class="fa fa-file-code-o"></i></div>
                <p>The website Description</p>
                <p><a class="btn btn-success pull-right" href="#"><i class="fa fa-pencil-square-o"></i> <?php echo $this->translate('Edit') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-globe"></i> Website #4</h3>
            </div>
            <div class="panel-body">
                <div class="icon"><i class="fa fa-file-code-o"></i></div>
                <p>The website Description</p>
                <p><a class="btn btn-success pull-right" href="#"><i class="fa fa-pencil-square-o"></i> <?php echo $this->translate('Edit') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>